substitutions:
  devicename: "garage-door-pico"
  upper_devicename: "Garage-Door pico"

esphome:
  name: "${devicename}"
  friendly_name: "${upper_devicename}"

rp2040:
  board: rpipicow
  framework:
    # Required until https://github.com/platformio/platform-raspberrypi/pull/36 is merged
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key01

# Enable over-the-air updates.
ota:
  safe_mode: true
  password: !secret ota_password01

# Connect to WiFi.
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "${upper_devicename}"
    password: !secret wifi_hotspot_password

# Enable Web server. Not yet supported on Pico.
#web_server:
#  port: 80

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

# LED on when door open.
output:
  # Built-in LED
  - platform: gpio
    pin:
      number: 32  # 25 for Pico (non-W)
      mode: output
    id: LED

# Binary sensor representing the
# garage-door status for each door. 
binary_sensor:
  # First Garage Door
  - platform: gpio
    pin:
      number: 3
      mode:
        input: true
        pullup: true
        output: false
        open_drain: false
        pulldown: false
      inverted: false
    name: First Garage Door
    id: first_garage_door
    device_class: door
    filters:
      - delayed_on: 10ms
    disabled_by_default: false
    on_state:
      then:
        - if:
            condition:
              or:
                - binary_sensor.is_on: first_garage_door
                - binary_sensor.is_on: second_garage_door
            then:
              - output.turn_on: LED
            else:
              - output.turn_off: LED

  # Second Garage Door
  - platform: gpio
    pin:
      number: 2
      mode:
        input: true
        pullup: true
        output: false
        open_drain: false
        pulldown: false
      inverted: false
    name: Second Garage Door
    id: second_garage_door
    device_class: door
    filters:
      - delayed_on: 10ms
    disabled_by_default: false
    on_state:
      then:
        - if:
            condition:
              or:
                - binary_sensor.is_on: first_garage_door
                - binary_sensor.is_on: second_garage_door
            then:
              - output.turn_on: LED
            else:
              - output.turn_off: LED
